### ISSUE TITLE
Running the Liquidctl plugin for FanControl causes Elgato FaceCam to disconnect and reconnect sporadically when camera is idle

### ISSUE THREAD

**Issue by notthatwillsmith** [jmarucha/FanControl.Liquidctl#13]
FYI, this is a repost from a bug I posted on the [FanControl issues board](https://github.com/Rem0o/FanControl.Releases/issues/1360). Troubleshooting there isolated the issue to this plugin. 

**Describe the bug**
Running FanControl with the liquidctl plugin installed and running causes my Elgato FaceCam to disconnect and reconnect sporadically when it's idle, causing Windows to make the "device disconnected/device reconnected chimes". I'm running Windows 11 Pro. 

When the camera is in use (OBS on, etc), it doesn't happen. I've confirmed that when FanControl is off, it doesn't happen. I'm using FanControl v.139, Elgato Cam Hub software is 1.5.0.801 and the camera firmware is v4.06. The only plugin I'm using with FanControl is the Liquidctl Plugin to pull liquid temps from my Kraken Z53. When I run FanControl with the liquidctl plugin disabled, it doesn't happen.

If it helps, when I use the current version of liquidctl to update the screen on my Kraken radiator, I don't have a similar problem.  

**Is there a log.txt file next to FanControl.exe with recent date entries?**
The recent date entries are due to me removing and reinstalling the Kraken drivers, because I thought it was the culprit. Here's a representative entry, just in case. 

`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
12/11/2022 5:00:24 PM: Unhandled exception in FanControl v1.0.0.0
12/11/2022 5:00:24 PM: System.Exception: liquidctl returned non-zero exit code 1. Last stderr output:
WARNING: python -m liquidctl.cli is deprecated, prefer python -m liquidctl
ERROR: unexpected OS error with NZXT Kraken Z (Z53, Z63 or Z73): OSError('read error')

   at FanControl.Liquidctl.LiquidctlCLIWrapper.LiquidctlCall(String arguments)
   at FanControl.Liquidctl.LiquidctlCLIWrapper.ReadStatus(String address)
   at FanControl.Liquidctl.LiquidctlDevice.LoadJSON()
   at FanControl.Liquidctl.LiquidctlPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Relevant hardware specs and setup**
Motherboard is a ROG Maximum Z790 Apex, there are Fractal RGB Aspect fans plugged into the motherboard headers, and the cooler/AIO is a NZXT Kraken Z53 with nothing else plugged into it.

**Comment by alexluckett** [comment]
Can confirm this relates to the liquidctl plugin. It hasn't been updated since 2022, however a [recent fork of the liquidctl plugin](https://github.com/sp00n/FanControl.Liquidctl) using a more recent version of liquidctl resolves this issue.
