### ISSUE TITLE
High CPU usage (Root of the problem)

### ISSUE THREAD

**Issue by brunoherrera** [jmarucha/FanControl.Liquidctl#20]
Follow up of [High CPU Usage (Antimalware Service Executable)](https://github.com/jmarucha/FanControl.Liquidctl/issues/15)

The root of the issue is that liquidctl.exe is constantly being opened and closed, I think 2 times per second, maybe more, checking resource monitor its constantly writing to %LocalAppData%/Temp, folders named something like:  _MEI154122, constantly modifying, deleting and creating thema gain and again, I added appdata folder to windows defender exclusions and it fixed the Antimalware Service Executable (MsMpEng.exe) high cpu issue, but opening and closing liquidctl.exe still makes the CPU work too much and temps rise anyways.

I'll disable the plugin and use HWiNFO instead untill this gets sorted out.

**Comment by cytrus224** [comment]
One way to fix it. Whitelist entire FanControl folder in Windows Defender. Instant fix to high CPU usage

**Comment by brunoherrera** [comment]
> One way to fix it. Whitelist entire FanControl folder in Windows Defender. Instant fix to high CPU usage

that's not a fix, liquidctl.exe is constantly being open and closed, making unnecessary writes to storage and taxing the cpu, rising temperatures

**Comment by brunoherrera** [comment]
@jmarucha maybe you can change liquidctl.exe out of plugins fodler so it isn't called by FanControl every second? 
I tried changing LiquidctlCLIWrapper.cs:11 to public static string liquidctlexe = "liquidctl\\liquidctl.exe"; 
But I'm a mess in windows with WSL and python3, it has some errors when executing build-liquidctl.sh, so becasue I don't even know if changing that line in wrapper.cs will work and re-path I'll just quit, but please move that .exe out of plugins folder

**Comment by SuspiciousActivity** [comment]
Since this issue was bugging me for some time now, I made a [custom fork of liquidctl](https://github.com/SuspiciousActivity/liquidctl) and [this plugin](https://github.com/SuspiciousActivity/FanControl.Liquidctl), which stops liquidctl from starting every second by using a custom made interactive mode in liquidctl. Haven't tested it at all on anything else than my computer, so use at your own risk if you want to. I'm just leaving this here if anyone more knowledgable is interested in using this approach and maybe commit a better change to liquidctl and this plugin and needs a base start which works. [Link](https://github.com/SuspiciousActivity/liquidctl/releases)

**Comment by momala454** [comment]
@SuspiciousActivity could you create pull requests on the original repos ?

**Comment by brunoherrera** [comment]
> Since this issue was bugging me for some time now, I made a [custom fork of liquidctl](https://github.com/SuspiciousActivity/liquidctl) and [this plugin](https://github.com/SuspiciousActivity/FanControl.Liquidctl), which stops liquidctl from starting every second by using a custom made interactive mode in liquidctl. Haven't tested it at all on anything else than my computer, so use at your own risk if you want to. I'm just leaving this here if anyone more knowledgable is interested in using this approach and maybe commit a better change to liquidctl and this plugin and needs a base start which works. [Link](https://github.com/SuspiciousActivity/FanControl.Liquidctl/releases)

works in my pc with Kraken X73, thanks!!!

**Comment by kromosomX** [comment]
> Since this issue was bugging me for some time now, I made a [custom fork of liquidctl](https://github.com/SuspiciousActivity/liquidctl) and [this plugin](https://github.com/SuspiciousActivity/FanControl.Liquidctl), which stops liquidctl from starting every second by using a custom made interactive mode in liquidctl. Haven't tested it at all on anything else than my computer, so use at your own risk if you want to. I'm just leaving this here if anyone more knowledgable is interested in using this approach and maybe commit a better change to liquidctl and this plugin and needs a base start which works. [Link](https://github.com/SuspiciousActivity/FanControl.Liquidctl/releases)

Hi, 

I tried to use your fork, but I get "LiquidctlPlugin could not initialize or has no sensors." message when starting Fan Control (v149). Liquidctl is working OK, beacause if run liquidctl status I get:

ASUS Aura LED Controller (experimental)
├── ARGB channels: 3
└──  RGB channels: 1
Asetek 690LC (assuming EVGA CLC)
├── Liquid temperature        34.7  °C
├── Fan speed                    0  rpm
├── Pump speed                2910  rpm
└── Firmware version      2.10.0.0

I think that it fails because  it's trying to interpre "Firmware version" as sensor data... because I get this in the Fan Control log:

9. 03. 2023 18:20:02: Newtonsoft.Json.JsonReaderException: Could not convert string to double: 2.10.0.0. Path '[1].status[3].value', line 1, position 587.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at FanControl.Liquidctl.LiquidctlCLIWrapper.ReadStatus()
   at FanControl.Liquidctl.LiquidctlPlugin.Load(IPluginSensorsContainer _container)
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()

**Comment by brunoherrera** [comment]
@kromosomX that should go in the issues section of the fork, I will cite the following [comment ](https://github.com/Rem0o/FanControl.Releases/issues/1488#issuecomment-1402973348) from @jmarucha in regards to the executable needed for liquidctl:

_In the case of that specific plugin, sadly yes, it would seem to be highly inefficient since it most likely call the exe at every update cycle ( 1 Hz ) to push and pull the information.

That's specific to that plugin implementation._

and since @SuspiciousActivity [solution](https://github.com/jmarucha/FanControl.Liquidctl/issues/20#issuecomment-1426453047) works for me I'll close this issue

**Comment by jmarucha** [comment]
@SuspiciousActivity have you tried talking to LiquidCTL team? The idea is amazing and I think they may be willing to get it upstream.

**Comment by xkutaca** [comment]
I am having issues with it recognizing a nzxt smart device 2, it works with my x72 but not the smart device 2
